[package]
name = "tunneld-protocol"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[lib]
name = "tunneld_protocol"
path = "src/lib.rs"

[dependencies]
tonic = "0.11.0"
prost = "0.12.6"

[build-dependencies]
tonic-build = "0.11.0"
